name: Deploy Latest Release to GCP VM

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH & Deploy Latest Release to GCP VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: tariq951
        key: ${{ secrets.GCP_VM_SSH_KEY }}
        script: |
          cd ~/proclubs-tracker
          git fetch --all --tags
          git checkout tags/${{ github.event.release.tag_name }}
          source venv/bin/activate
          pip install -r requirements.txt --quiet
          sudo systemctl restart proclubs-bot
          echo "Successfully deployed ${{ github.event.release.tag_name }} to GCP VM!"
